---
- name: Fire-up docker container used for building virtualenv
  docker_container:
    name: django_stack_venv
    image: "{{ django_stack_venv_docker_image }}"
    command: "{{ django_stack_venv_docker_cmd|default(omit) }}"
    capabilities: "{{ django_stack_venv_docker_cap|default(omit) }}"
    volumes: "{{ django_stack_venv_docker_volumes + [tmp_dir+':/venv-export'] }}"
    env: "{{ django_stack_venv_env | default(omit) }}"
  delegate_to: localhost
  become: no

- name: Add virtualenv docker to current play inventory
  add_host:
    name: django_stack_venv
    ansible_connection: docker

- block:
    - name: Install system dependencies
      apt:
        name: "{{ item }}"
        update_cache: yes
        cache_valid_time: 3600
      with_items: "{{ django_stack_pkgs }}"
      tags: ['pkgs']

    # Necessary because there is no way to pass --relocatable to virtualenv from
    # pip module, so docker build needs to match remote server
    - name: Create virtualenv base dir to match remote server
      file:
        state: directory
        path: "{{ django_stack_gcorn_home }}"
        recurse: yes

    - name: Create virtualenv and ensure base packages installed
      pip:
        name: "{{ item }}"
        virtualenv: "{{ django_stack_venv_dir }}"
        virtualenv_python: "{{ django_stack_venv_python }}"
        virtualenv_site_packages: "{{ django_stack_venv_sitepackage }}"
        extra_args: "-U"
      no_log: "{{ django_stack_venv_no_log }}"
      with_items: "{{ ['pip==20.0.2'] + django_stack_venv_base_pkgs }}"

    - name: Optional commands to run prior to req install
      command: "{{ item }}"
      with_items: "{{ django_stack_venv_cmds }}"

    - name: Setup virtualenv from requirements file
      pip:
        requirements: "/venv-export/git/{{ django_stack_requirements_path }}"
        virtualenv: "{{ django_stack_venv_dir }}"
        virtualenv_python: "{{ django_stack_venv_python }}"
        virtualenv_site_packages: "{{ django_stack_venv_sitepackage }}"
      no_log: "{{ django_stack_venv_no_log }}"
      when: django_stack_github_requirements_path is not defined

    - name: Setup virtualenv from requriements file with requisite hashes
      pip:
        requirements: "/venv-export/git/{{ django_stack_requirements_path }}"
        virtualenv: "{{ django_stack_venv_dir }}"
        virtualenv_python: "{{ django_stack_venv_python }}"
        virtualenv_site_packages: "{{ django_stack_venv_sitepackage }}"
        extra_args: --require-hashes
      no_log: "{{ django_stack_venv_no_log }}"
      when: django_stack_github_requirements_path is defined

    - name: Setup virtualenv additional github requirements
      pip:
        requirements: "/venv-export/git/{{ django_stack_github_requirements_path }}"
        virtualenv: "{{ django_stack_venv_dir }}"
        virtualenv_python: "{{ django_stack_venv_python }}"
        virtualenv_site_packages: "{{ django_stack_venv_sitepackage }}"
      no_log: "{{ django_stack_venv_no_log }}"
      when: django_stack_github_requirements_path is defined

    # Hack around a probable bug in pip 20.1b1 that leaves INSTALLER and
    # RECORD files unreadable by any other user than root, which will prevent
    # rsyncing them as an unprivileged user from outside the container
    - name: Ensure contents of virtualenv are world-readable
      file:
        path: "{{ django_stack_venv_dir }}"
        recurse: yes
        mode: o=rX

    - name: Move remote virtualenv into docker exportable filespace
      command: mv {{django_stack_venv_dir}} /venv-export/{{django_stack_app_name}}

  delegate_to: django_stack_venv
  become: no

- name: Copy over locally built virtualenv to remote server
  synchronize:
    src: "{{ tmp_dir }}/{{ django_stack_app_name }}/"
    dest: "{{ django_stack_venv_dir }}/"
    recursive: yes
    perms: yes
    delete: yes
  become_user: "{{ django_stack_gcorn_user }}"
  become: yes
