---
- name: Ensure run directory exists for gunicorn
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ django_stack_gcorn_user }}"
    group: "{{ django_stack_gcorn_group }}"
  with_items:
    - /run/gunicorn
    - "/var/log/{{ django_stack_app_name }}"

- name: Define temporary run file
  lineinfile:
    dest: /etc/tmpfiles.d/gunicorn.conf
    line: "d /run/gunicorn 0755 {{ django_stack_gcorn_user }} {{ django_stack_gcorn_group }} -"
    create: yes

- name: Drop service and socket file
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dst }}"
  with_items:
    - src: gunicorn.j2
      dst: /etc/systemd/system/gunicorn.service
  register: systemd_files

- name: Refresh systemd files
  systemd:
    daemon_reload: yes
    name: "{{ item }}"
    state: started
    enabled: True
  when: systemd_files|changed
  with_items: ['gunicorn.service']
