---
- name: Drop service and socket file
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dst }}"
  with_items:
    - src: gunicorn.j2
      dst: /etc/systemd/system/gunicorn-{{ django_stack_active_gcorn_svc }}.service
  notify: Refresh systemd files

- name: Lay out upstream web server snippet file(s)
  template:
    dest: "{{ item.path }}"
    src: "{{ item.template }}"
  notify: "{{ item.notify }}"
  with_items: "{{ django_stack_www_snippets }}"
