---
- include: pull_sitecode.yml
  when: django_stack_deploy_sitecode
  tags: ['git']

- include: npm.yml
  tags: ['npm']

- include: django_service.yml
  tags: ['django']

- include: gunicorn.yml
  tags: ['gunicorn']
