---

- include: setup.yml
  tags: ['always']

- include: pull_sitecode.yml
  when: django_stack_git_repo != []
  tags: ['git']

- include: npm.yml
  tags: ['npm']

- include: django_service.yml
  tags: ['django']

- include: gunicorn.yml
  tags: ['gunicorn']
