---

- include: setup.yml
  tags: always

- include: check_git.yml

- include: pull_sitecode.yml

- include: npm.yml
  when:
    - current_git_hash != orig_git_hash

- include: build-venv.yml
  when:
    - current_git_hash != orig_git_hash

- include: push_sitecode.yml
  when:
    - current_git_hash != orig_git_hash

- include: django_service.yml
  tags: django

- include: gunicorn.yml
  tags: gunicorn
