---
- block:
    - name: If grsec, add paxflags cmd to node
      set_fact:
        node_grsec_image: "node_grsec"
      when: ansible_kernel.endswith('grsec')

    - name: Prepare node image with pax flags
      docker_image:
        name: "node_grsec:{{ django_stack_node_ver }}"
        dockerfile: "{{ role_path }}/docker/NodeDockerfile"
        path: ../../
        tag: "{{ django_stack_node_ver }}"
      when: ansible_kernel.endswith('grsec')

    - name: Node local docker builder
      docker_container:
        name: pf_tracker_node
        image: "{{ node_grsec_image|default('node') }}:{{ django_stack_node_ver }}"
        volumes:
          - "{{ tmp_dir_git }}:{{ active_deploy_dir }}"
          - "{{ tmp_dir }}:/status"
        state: started
        working_dir: "{{ active_deploy_dir }}"
        command: /bin/ash -c "{{django_stack_npm_install_cmd}}; {{npm_touch}}"
        user: node
        recreate: "yes"

    - name: Wait for node logic to finish up
      wait_for:
        path: "{{ tmp_dir }}/npm.done"

  become: "no"
  delegate_to: localhost
