---

- name: Ensure git dependencies exist
  package:
    name: "{{ item }}"
  with_items: "{{ django_stack_git_pkgs }}"

- name: Ensure key dest folders exist
  file:
    state: directory
    dest: "{{ item.dest|default(django_stack_gcorn_home+'/.ssh/') }}"
    owner: "{{ item.owner|default(django_stack_gcorn_user) }}"
    group: "{{ item.group|default(django_stack_gcorn_group) }}"
    mode: "{{ item.mode|default(0700) }}"
  with_items: "{{ django_stack_git_deploy }}"
  no_log: true

- name: Lay-down git deploy keys
  copy:
    dest: "{{ item.dest|default(django_stack_gcorn_home+'/.ssh/github_deploy') }}"
    content: "{{ item.key }}"
    owner: "{{ item.owner|default(django_stack_gcorn_user) }}"
    group: "{{ item.group|default(django_stack_gcorn_group) }}"
    mode: "{{ item.mode|default(0700) }}"
  with_items: "{{ django_stack_git_deploy }}"
  no_log: true

- name: Pull down site code
  git:
    repo: "{{ item.url }}"
    version: "{{ item.branch|default('master') }}"
    dest: "{{ item.dest|default(django_stack_deploy_dir) }}"
    key_file: "{{ item.key|default(omit) }}"
    force: "{{ item.force|default(omit) }}"
    accept_hostkey: "{{ item.accept_hostkey|default('yes') }}"
    recursive: "{{ item.recursive|default('yes') }}"
  register: git_pull
  with_items: "{{ django_stack_git_repo }}"
