---
- name: Push codebase to remote server's active dir
  synchronize:
    src: "{{ tmp_dir }}/git/"
    dest: "{{ active_deploy_dir }}/"
    recursive: yes
    perms: no
    delete: yes
  notify: Update active svc remote fact
  become_user: "{{ django_stack_gcorn_user }}"
  become: yes

- name: Recursively set permissions
  file:
    dest: "{{ active_deploy_dir }}/"
    owner: "{{ django_stack_gcorn_user }}"
    group: "{{ django_stack_gcorn_user }}"
    recurse: yes
