---

- name: Configure gunicorn user
  user:
    name: "{{ django_stack_gcorn_user }}"
    createhome: yes
    home: "{{ django_stack_gcorn_home }}"
    shell: /bin/bash

- name: Establish needed directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ django_stack_gcorn_user }}"
    group: "{{ django_stack_gcorn_group }}"
  with_items:
    - "{{ django_stack_static_root }}"
    - "{{ django_stack_media_root }}"
    - "{{ django_stack_logdir }}"

- name: Touch log file
  file:
    state: touch
    path: "{{ django_stack_logdir }}/{{ django_stack_logfile }}"
    owner: "{{ django_stack_gcorn_user }}"
    group: "{{ django_stack_gcorn_group }}"
  when: django_stack_logdir != ''
  changed_when: false
