---
driver:
  name: docker
lint:
  name: yamllint
  options:
    config-file: .yamllint
platforms:
  - name: debian_jessie_django_stack_ci
    image: quay.io/freedomofpress/ci-webserver
    command: /lib/systemd/systemd
    capabilities:
      - SYS_ADMIN
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    published_ports:
      - 4443:443
    groups:
      - django
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: ci_rsync
  converge_sequence:
    - converge
  test_sequence:
    - converge
    - idempotence
    - lint
    - verify
    - destroy
